SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS BM_CONTACT_SECRET_PERSON;
DROP TABLE IF EXISTS BM_RECEIVE_CONFIDENTIAL;


/* Create Tables */

-- 接触和知悉绝密级商业秘密文件人员表
CREATE TABLE BM_CONTACT_SECRET_PERSON
(
	CONTACT_SECRET_PERSON_ID VARCHAR(39) NOT NULL,
	-- 文件名称
	SECRET_FILE_NAME VARCHAR(300) NOT NULL COMMENT '文件名称',
	-- 发文机关
	DISPATCH_ORGAN VARCHAR(300) COMMENT '发文机关',
	-- 发文日期
	ISSUED_DATE DATE COMMENT '发文日期',
	-- 收文日期
	RECEIVE_DATE DATE COMMENT '收文日期',
	-- 数量
	FILE_NUM INT COMMENT '数量',
	-- 人员姓名
	CONTACT_PERSON_NAME VARCHAR(500) COMMENT '人员姓名',
	-- 接触或知悉时间
	CONTACT_DATE DATE COMMENT '接触或知悉时间',
	-- 接触类型
	CONTACT_TYPE INT COMMENT '接触类型',
	-- 接触方式（接触：1；知悉：2；其它：100；）
	CONTACT_WAY INT COMMENT '接触方式（接触：1；知悉：2；其它：100；）',
	-- 承办人
	UNDERTAKER VARCHAR(300) COMMENT '承办人',
	-- 审批领导
	APPROVED_LEADER VARCHAR(300) COMMENT '审批领导',
	-- 状态
	STATUS INT COMMENT '状态',
	CREATE_PERSON VARCHAR(39),
	CREATE_TIME DATE,
	MODIFY_PERSON VARCHAR(39),
	MODIFY_TIME DATE,
	CREATE_ORGAN VARCHAR(39),
	PRIMARY KEY (CONTACT_SECRET_PERSON_ID)
) COMMENT = '接触和知悉绝密级商业秘密文件人员表';


CREATE TABLE BM_RECEIVE_CONFIDENTIAL
(
	RECEIVE_CONFIDENTIAL_ID VARCHAR(39) NOT NULL,
	-- 密件名称
	CONFIDENTIAL_NAME VARCHAR(300) NOT NULL COMMENT '密件名称',
	-- 密件内容
	CONFIDENTIAL_CONTENT TEXT NOT NULL COMMENT '密件内容',
	-- 密级
	SECURITY_LEVEL INT NOT NULL COMMENT '密级',
	-- 时间
	RECEIVER_TIME DATE NOT NULL COMMENT '时间',
	-- 文号
	DOC_NUM VARCHAR(300) NOT NULL COMMENT '文号',
	-- 载体形式
	CARRIER_FORMAT INT NOT NULL COMMENT '载体形式',
	-- 数量
	FILE_NUM INT NOT NULL COMMENT '数量',
	-- 状态
	STATUS INT NOT NULL COMMENT '状态',
	-- 创建人
	CREATE_PERSON VARCHAR(39) NOT NULL COMMENT '创建人',
	-- 创建时间
	CREATE_TIME DATE NOT NULL COMMENT '创建时间',
	-- 修改人
	MODIFY_PERSON VARCHAR(39) COMMENT '修改人',
	-- 修改时间
	MODIFY_TIME DATE COMMENT '修改时间',
	-- 创建单位
	CREATE_ORGAN VARCHAR(39) NOT NULL COMMENT '创建单位',
	PRIMARY KEY (RECEIVE_CONFIDENTIAL_ID)
);




