SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS BM_SECRET_NETWORK_MANAGERS;
DROP TABLE IF EXISTS BM_SECRET_NETWORK;




/* Create Tables */

-- 涉密网络管理
CREATE TABLE BM_SECRET_NETWORK
(
	SECRET_NETWORK_ID VARCHAR(39) NOT NULL,
	-- 建成时间
	BUILD_TIME DATE COMMENT '建成时间',
	-- 承建单位
	CONSTRUCTION_UNIT VARCHAR(300) COMMENT '承建单位',
	-- 审批部门
	APPROVAL_DEPARTMENT VARCHAR(300) COMMENT '审批部门',
	-- 审批时间
	APPROVAL_TIME DATE COMMENT '审批时间',
	-- 文号
	DOC_NUM VARCHAR(300) COMMENT '文号',
	-- 状态
	STATUS INT COMMENT '状态',
	CREATE_PERSON VARCHAR(39),
	CREATE_TIME DATE,
	MODIFY_PERSON VARCHAR(39),
	MODIFY_TIME DATE,
	CREATE_ORGAN VARCHAR(39),
	PRIMARY KEY (SECRET_NETWORK_ID)
) COMMENT = '涉密网络管理';


CREATE TABLE BM_SECRET_NETWORK_MANAGERS
(
	SECRET_NETWORK_MANAGERS_ID VARCHAR(39) NOT NULL,
	SECRET_NETWORK_ID VARCHAR(39) NOT NULL,
	-- 管理员姓名
	MANAGER_NAME VARCHAR(300) COMMENT '管理员姓名',
	-- 职务
	MANAGER_POST VARCHAR(300) COMMENT '职务',
	-- 学历
	LEARNING VARCHAR(100) COMMENT '学历',
	-- 毕业学校
	GRADUATE_SCHOOL VARCHAR(300) COMMENT '毕业学校',
	-- 是否参加过计算机保密业务培训（是：1；否：0；）
	IS_PARTICIPATED_SECRE INT COMMENT '是否参加过计算机保密业务培训（是：1；否：0；）',
	-- 状态
	STATUS INT COMMENT '状态',
	CREATE_PERSON VARCHAR(39),
	CREATE_TIME DATE,
	MODIFY_PERSON VARCHAR(39),
	MODIFY_TIME DATE,
	CREATE_ORGAN VARCHAR(39),
	PRIMARY KEY (SECRET_NETWORK_MANAGERS_ID)
);



/* Create Foreign Keys */

ALTER TABLE BM_SECRET_NETWORK_MANAGERS
	ADD FOREIGN KEY (SECRET_NETWORK_ID)
	REFERENCES BM_SECRET_NETWORK (SECRET_NETWORK_ID)
	ON UPDATE RESTRICT
	ON DELETE RESTRICT
;



