SET SESSION FOREIGN_KEY_CHECKS=0;

/* Drop Tables */

DROP TABLE IF EXISTS BM_DEPARTMENTWEBSITE;
DROP TABLE IF EXISTS BM_INFORMATION_REVIEW;
DROP TABLE IF EXISTS BM_PUBLICITYEDUCATION;
DROP TABLE IF EXISTS BM_UNDERTAKETASK;




/* Create Tables */

CREATE TABLE BM_DEPARTMENTWEBSITE
(
	DEPARTMENTWEBSITE_ID VARCHAR(39) NOT NULL,
	-- 网站名称
	WEBSITE_NAME VARCHAR(300) COMMENT '网站名称',
	-- 管理员姓名（多人）
	ADMIN_NAME VARCHAR(300) COMMENT '管理员姓名（多人）',
	-- 管理员职务
	ADMIN_POST VARCHAR(200) COMMENT '管理员职务',
	-- 网站所属部门
	DEPARTMENT VARCHAR(39) COMMENT '网站所属部门',
	STATUS INT DEFAULT 1,
	CREATE_PERSON VARCHAR(39),
	CREATE_TIME DATE,
	MODIFY_PERSON VARCHAR(39),
	MODIFY_TIME DATE,
	CREATE_ORGAN VARCHAR(39),
	PRIMARY KEY (DEPARTMENTWEBSITE_ID)
);

-- 信息发布保密审查情况
CREATE TABLE BM_INFORMATION_REVIEW
(
	INFORMATION_REVIEW_ID VARCHAR(39) NOT NULL,
	-- 标题
	TITLE VARCHAR(500) COMMENT '标题',
	-- 信息内容
	CONTENT TEXT COMMENT '信息内容',
	-- 信息来源（字典表，复选）
	INFORMATION_SOURCES VARCHAR(200) COMMENT '信息来源（字典表，复选）',
	-- 承办部门
	UNDERTAKING_DEPARTMENT VARCHAR(39) COMMENT '承办部门',
	-- 发布途径(字典表，复选)
	RELEASE_WAY VARCHAR(200) COMMENT '发布途径(字典表，复选)',
	-- 部门初审意见
	INITIAL_OPINIONS VARCHAR(2000) COMMENT '部门初审意见',
	-- 专业审核人审核意见
	PROFESSIONAL_OPINION VARCHAR(2000) COMMENT '专业审核人审核意见',
	-- 单位领导签批意见
	UNIT_LEADERS_OPINIONS VARCHAR(2000) COMMENT '单位领导签批意见',
	-- 状态
	STATUS INT DEFAULT 1 COMMENT '状态',
	CREATE_PERSON VARCHAR(39),
	CREATE_TIME DATE,
	MODIFY_PERSON VARCHAR(39),
	MODIFY_TIME DATE,
	CREATE_ORGAN VARCHAR(39),
	-- 备注
	REMARK VARCHAR(3000) COMMENT '备注',
	PRIMARY KEY (INFORMATION_REVIEW_ID)
) COMMENT = '信息发布保密审查情况';


-- 宣传教育培训情况
CREATE TABLE BM_PUBLICITYEDUCATION
(
	-- id
	PUBLICITYEDUCATION_ID VARCHAR(39) NOT NULL COMMENT 'id',
	-- 培训时间
	TRAIN_TIME DATE COMMENT '培训时间',
	-- 形式
	FORM VARCHAR(200) COMMENT '形式',
	-- 范围
	TRAIN_RANGE VARCHAR(200) COMMENT '范围',
	-- 参加人数
	PARTICIPANTS_NUM INT COMMENT '参加人数',
	-- 主要内容
	CONTENT TEXT COMMENT '主要内容',
	STATUS INT DEFAULT 1,
	CREATE_PERSON VARCHAR(39),
	CREATE_TIME DATE,
	MODIFY_PERSON VARCHAR(39),
	MODIFY_TIME DATE,
	CREATE_ORGAN VARCHAR(39),
	PRIMARY KEY (PUBLICITYEDUCATION_ID)
) COMMENT = '宣传教育培训情况';


-- 宣传教育培训情况
CREATE TABLE BM_UNDERTAKETASK
(
	-- id
	UNDERTAKETASK_ID VARCHAR(39) NOT NULL COMMENT 'id',
	-- 课题（试点）名称
	TASK_NAME VARCHAR(200) COMMENT '课题（试点）名称',
	-- 下达单位
	RELEASE_UNIT VARCHAR(39) COMMENT '下达单位',
	-- 承办人
	UNDERTAKER VARCHAR(200) COMMENT '承办人',
	-- 完成时间
	COMPLETE_TIME DATE COMMENT '完成时间',
	-- 具体成效
	SPECIFIC_RESULTS TEXT COMMENT '具体成效',
	STATUS INT DEFAULT 1,
	CREATE_PERSON VARCHAR(39),
	CREATE_TIME DATE,
	MODIFY_PERSON VARCHAR(39),
	MODIFY_TIME DATE,
	CREATE_ORGAN VARCHAR(39),
	PRIMARY KEY (UNDERTAKETASK_ID)
) COMMENT = '宣传教育培训情况';



